### ISSUE TITLE
Plugins which are not ...

### ISSUE THREAD

**Issue by makefu** [k4cg/nichtparasoup#88]
... Plugins :wink: 

The basic idea of a plugin is to 'plug it in' and have the framework figuring out the rest. When creating a new plugin it is not enough to simply create a new crawler file in crawler/ but you actually need to touch nichtparasoup.py to import the new crawler AND define the url in this file plus the logic how to handle tags.

The plugins themselve should provide have logic to return a crawler with the correct urls and optional parameters like search tags.

Besides that :+1:

**Comment by noqqe** [comment]
Hey @makefu 

I agree with your opinion on plugins and how they should work. :+1: 

But where does it come from? The word Plugin doesn't exist in the code or the docs :) 
Also we never looked at crawlers in a "plugin" way. 

Would you prefer having crawlers in a plugin way? At least thats what I understand

**Comment by makefu** [comment]
Ok, you tactically ignored the word plugin i guess. Maybe it was just an extrapolation of mine but the 'crawler' are just so close to being self-contained plugins and then ... BAM hard-coded urls in the main class :laughing: 

I was looking into stripping out the crawler part of the parasoup and i cried a bit inside seeing the crawler code being so close to being actually really cool.

I may try to fix the design decision for my fork as it is not the most important thing to do.

**Comment by noqqe** [comment]
yep, but we're open to the conversion to fully pluggable crawlers. At least from my side, cannot see any disadvantages. What do you think @jkowalleck ?

**Comment by jkowalleck** [comment]
hey @makefu drop a pull request. i am pretty keen on your solutions.

**Comment by makefu** [comment]
i wrote a first working example for a plugging architecture.
have a look at https://github.com/makefu/dochparasoup/blob/a8add7e352a7d0e2dc3f15b91c945b1d93feb429/dochparasoup/plugins/bildschirmarbeiter.py#L14 .

The plugging architecture is based on yapsy and the basic idea is that each plugin exposes a minimal Interface. 

The interface exposes a factory function which builds crawlers with the right uris based on the given categories. It returns a list of appropriate crawlers.

**Comment by makefu** [comment]
i finished the rewrite for the crawler via 07e90f519845cf958f1a6a33d3310d2160953290, i have not yet rewritten the nichtparasoup code as i am only interested in the crawlers which are in a working state again :)

The code surely can be refactored even more but imho it is good enough now :D

**Comment by jkowalleck** [comment]
hello @makefu 

plugins(#129) will be available in the upcoming version 2.2
